// src/views/SignUp/SignUp.tsx
import { Formik } from "formik";
import { SignUpForm, SignUpWrapper } from "@/views/SignUp/SignUp.styled.ts";
import { auth } from "@/firebase";
import { createUserWithEmailAndPassword, updateProfile } from "firebase/auth";
import { useNavigate } from "react-router-dom";
import { useState } from "react";
import FormikInput from "@/components/FormikInput/FormikInput.tsx";

interface SignUpFormValues {
  fullName: string;
  email: string;
  password: string;
  confirmPassword: string;
}

const SignUp = () => {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);

  const initialValues: SignUpFormValues = {
    fullName: "",
    email: "",
    password: "",
    confirmPassword: ""
  };

  const handleValidation = (values: SignUpFormValues) => {
    interface SignUpValidationValues {
      fullName?: string;
      email?: string;
      password?: string;
      confirmPassword?: string;
    }
    const errors: SignUpValidationValues = {};

    if (!values.fullName) {
      errors.fullName = "Full name is required";
    }

    if (!values.email) {
      errors.email = "Email is required";
    }

    if (!values.email?.includes("@")) {
      errors.email = "Email is invalid";
    }

    if (!values.password) {
      errors.password = "Password is required";
    }

    if (values.password.length < 6) {
      errors.password = "Password should be at least 6 characters";
    }

    if (!values.confirmPassword) {
      errors.confirmPassword = "Confirmation password is required";
    }

    if (values.password !== values.confirmPassword) {
      errors.confirmPassword = "Passwords must match";
    }

    return errors;
  };

  const handleSubmit = async (values: SignUpFormValues) => {
    try {
      setIsLoading(true);
      await createUserWithEmailAndPassword(auth, values.email, values.password);

      if (auth?.currentUser) {
        await updateProfile(auth?.currentUser, {
          displayName: values.fullName
        });
      } else {
        console.log("Could not set the name");
      }

      return navigate("/");
    } catch (error: any) {
      console.log(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <SignUpWrapper>
      <h2 className="sign-up__header">Sign Up</h2>
      <Formik initialValues={initialValues} onSubmit={handleSubmit} validate={handleValidation}>
        {({ errors, touched, isValidating }) => (
          <SignUpForm>
            <FormikInput
              name="fullName"
              labelName="Full Name"
              errorMessage={errors.fullName}
              touched={touched.fullName}
            />
            <FormikInput
              name="email"
              labelName="Email"
              errorMessage={errors.email}
              touched={touched.email}
            />
            <FormikInput
              name="password"
              labelName="Password"
              type="password"
              errorMessage={errors.password}
              touched={touched.password}
            />
            <FormikInput
              name="confirmPassword"
              labelName="Confirm Password"
              type="password"
              errorMessage={errors.confirmPassword}
              touched={touched.confirmPassword}
            />
            <button disabled={isValidating || isLoading} className="sign-up__button" type="submit">
              Sign Up
            </button>
          </SignUpForm>
        )}
      </Formik>
    </SignUpWrapper>
  );
};

export default SignUp;

// src/Authentication/Views/SignUp.vue
<script setup lang="ts">
import { ref } from "vue";
import PageContainer from "@/layouts/default/PageContainer.vue";
import FormContainer from "@/commons/components/FormContainer.vue";
import { supabase } from "@/lib/supabaseClient";
import { useRouter } from "vue-router";
import SwitchAuthenticationView from "@/Authentication/components/SwitchAuthenticationView.vue";

const router = useRouter();

const email = ref("");
const emailRules = [
  (value: string) => /.+@.+/.test(value) || "Invalid Email address",
];

const password = ref("");
const passwordRules = [
  (value: string) =>
    value.length >= 6 || "Password must be at least 8 characters",
];

const repeatPassword = ref("");
const repeatPasswordRules = [
  (value: string) => value === password.value || "Passwords do not match",
];

const loading = ref(false);

const handleSubmit = async () => {
  loading.value = true;
  const { error } = await supabase.auth.signUp({
    email: email.value,
    password: password.value,
  });

  if (error) {
    console.log(error.message);
    loading.value = false;
    return;
  }

  await router.replace({ name: "Home" });
  loading.value = false;
};
</script>

<template>
  <PageContainer title="Sign up">
    <FormContainer
      submit-button-title="sign up"
      @submit="handleSubmit"
      :loading="loading"
    >
      <v-text-field
        label="Email"
        :rules="emailRules"
        v-model="email"
        required
      />
      <v-text-field
        label="Password"
        :rules="passwordRules"
        v-model="password"
        type="password"
        required
      />
      <v-text-field
        label="Repeat password"
        :rules="repeatPasswordRules"
        v-model="repeatPassword"
        type="password"
        required
      />

      <template #after-submit>
        <SwitchAuthenticationView sign-in />
      </template>
    </FormContainer>
  </PageContainer>
</template>
